"""
LLMManager - LLM Orchestration (Langchain + Ollama)
Manages conversation history and generates LLM responses.
"""

import logging
from typing import Optional

from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnableSequence
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory

import config

logger = logging.getLogger(__name__)


class LLMManager:

    def __init__(
        self,
        model: str = config.LLM_MODEL,
        base_url: str = config.LLM_BASE_URL,
        temperature: float = config.LLM_TEMPERATURE):

        logger.info(
            "Starting LLMManager - model=%s, url=%s, temp=%.1f",
            model, base_url, temperature,
        )

        self._llm = ChatOllama(
            model=model,
            base_url=base_url,
            temperature=temperature,
        )

        self._store: dict[str, ChatMessageHistory] = {}
        self._system_prompt: str = "You are a helpful assistant."
        self._chain = None
        self._chain_with_history = None
        self._build_chain()
        logger.info("LLMManager ready.")

    def _get_session_history(self, session_id: str) -> ChatMessageHistory:
        """Returns the message history for a given session, or creates it if missing."""
        if session_id not in self._store:
            self._store[session_id] = ChatMessageHistory()
        return self._store[session_id]

    def _build_chain(self):
        """(Re)builds the prompt template and chain."""
        prompt = ChatPromptTemplate.from_messages([
            ("system", self._system_prompt),
            MessagesPlaceholder(variable_name="history"),
            ("human", "{question}"),
        ])
        
        # prompt fills the template and llm sends it to Ollama
        self._chain = RunnableSequence(prompt, self._llm)
        self._chain_with_history = RunnableWithMessageHistory(
            self._chain,
            self._get_session_history,
            input_messages_key="question",
            history_messages_key="history",
        )

    def set_system_prompt(self, prompt: str):
        """
        Updates the system prompt and rebuilds the chain.

        Args:
            prompt: New system prompt text.
        """
        self._system_prompt = prompt
        self._build_chain()
        logger.info("System prompt updated.")

    def get_response(self, user_message: str, session_id: str = "default") -> str:
        """
        Generates an LLM response to the user's message.

        Args:
            user_message: The text spoken by the user.
            session_id: Conversation session ID.

        Returns:
            Text response generated by the LLM.
        """
        logger.info(
            "LLM request - session=%s, message='%s'",
            session_id, user_message[:80],
        )
        invoke_config = {"configurable": {"session_id": session_id}}
        response = self._chain_with_history.invoke(
            {"question": user_message},
            config=invoke_config,
        )
        result = response.content
        logger.info("LLM response - '%s'", result[:80])
        return result

    def get_history(self, session_id: str = "default") -> list:
        """
        Returns the message history for a specific session.

        Args:
            session_id: Conversation session ID.

        Returns:
            List of messages.
        """
        history = self._get_session_history(session_id)
        return history.messages

    def clear_history(self, session_id: str = "default"):
        """
        Clears the message history for a specific session.

        Args:
            session_id: Conversation session ID.
        """
        if session_id in self._store:
            self._store[session_id].clear()
            logger.info("History cleared for session %s.", session_id)
