"""
LLMManager - LLM Orchestration (Langchain)
Manages conversation history and generates LLM responses.
Supports Local (Ollama) and OpenAI (cloud) providers.
"""

import logging

from langchain_core.messages import SystemMessage, HumanMessage, RemoveMessage
from langgraph.graph import START, StateGraph, MessagesState
from langgraph.checkpoint.memory import InMemorySaver

import config

logger = logging.getLogger(__name__)


class LLMManager:

    def __init__(
        self,
        provider: str = config.DEFAULT_PROVIDER,
        api_key: str | None = None,
        temperature: float = config.LLM_TEMPERATURE):

        self._provider = provider

        if provider == "OpenAI":
            from langchain_openai import ChatOpenAI
            logger.info("Starting LLMManager - provider=OpenAI, model=%s", config.OPENAI_MODEL)
            self._llm = ChatOpenAI(
                model=config.OPENAI_MODEL,
                api_key=api_key,
                temperature=temperature,
            )
        else:
            from langchain_ollama import ChatOllama
            logger.info("Starting LLMManager - provider=Local, model=%s", config.LOCAL_LLM_MODEL)
            self._llm = ChatOllama(
                model=config.LOCAL_LLM_MODEL,
                base_url=config.LOCAL_LLM_BASE_URL,
                temperature=temperature,
            )

        self._system_prompt: str = "You are a helpful assistant."
        self._memory = InMemorySaver()
        self._app = None
        self._build_chain()
        logger.info("LLMManager ready.")

    def _build_chain(self):
        """(Re)builds the state graph app."""
        workflow = StateGraph(state_schema=MessagesState)

        def call_model(state: MessagesState):
            messages = state["messages"]
            # Prepend system prompt to the messages list
            prompt_messages = [SystemMessage(content=self._system_prompt)] + messages
            response = self._llm.invoke(prompt_messages)
            return {"messages": response}

        workflow.add_node("model", call_model)
        workflow.add_edge(START, "model")

        self._app = workflow.compile(checkpointer=self._memory)

    def set_system_prompt(self, prompt: str):
        """
        Updates the system prompt.

        Args:
            prompt: New system prompt text.
        """
        self._system_prompt = prompt
        logger.info("System prompt updated.")

    def get_response(self, user_message: str, session_id: str = "default") -> str:
        """
        Generates an LLM response to the user's message.

        Args:
            user_message: The text spoken by the user.
            session_id: Conversation session ID.

        Returns:
            Text response generated by the LLM.
        """
        logger.info(
            "LLM request - session=%s, message='%s'",
            session_id, user_message[:80],
        )
        invoke_config = {"configurable": {"thread_id": session_id}}
        response = self._app.invoke(
            {"messages": [HumanMessage(content=user_message)]},
            config=invoke_config,
        )
        result = response["messages"][-1].content
        logger.info("LLM response - '%s'", result[:80])
        return result

    def get_history(self, session_id: str = "default") -> list:
        """
        Returns the message history for a specific session.

        Args:
            session_id: Conversation session ID.

        Returns:
            List of messages.
        """
        config = {"configurable": {"thread_id": session_id}}
        state = self._app.get_state(config)
        if state and hasattr(state, "values") and "messages" in state.values:
            return state.values["messages"]
        return []

    def clear_history(self, session_id: str = "default"):
        """
        Clears the message history for a specific session.

        Args:
            session_id: Conversation session ID.
        """
        config = {"configurable": {"thread_id": session_id}}
        state = self._app.get_state(config)
        if state and hasattr(state, "values") and "messages" in state.values:
            messages_to_remove = [
                RemoveMessage(id=m.id)
                for m in state.values["messages"]
                if getattr(m, "id", None) is not None
            ]
            if messages_to_remove:
                self._app.update_state(config, {"messages": messages_to_remove})
            logger.info("History cleared for session %s.", session_id)
