"""
LLMManager - LLM Orchestration (Langchain)
Manages conversation history and generates LLM responses.
Supports Local (Ollama) and OpenAI (cloud) providers.
"""

import logging
from collections import defaultdict

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

import config

logger = logging.getLogger(__name__)


class LLMManager:

    def __init__(
        self,
        provider: str = config.DEFAULT_PROVIDER,
        api_key: str | None = None,
        temperature: float = config.LLM_TEMPERATURE):

        self._provider = provider

        if provider == "OpenAI":
            from langchain_openai import ChatOpenAI
            logger.info("Starting LLMManager - provider=OpenAI, model=%s", config.OPENAI_MODEL)
            self._llm = ChatOpenAI(
                model=config.OPENAI_MODEL,
                api_key=api_key,
                temperature=temperature,
            )
        else:
            from langchain_ollama import ChatOllama
            logger.info("Starting LLMManager - provider=Local, model=%s", config.LOCAL_LLM_MODEL)
            self._llm = ChatOllama(
                model=config.LOCAL_LLM_MODEL,
                base_url=config.LOCAL_LLM_BASE_URL,
                temperature=temperature,
            )

        self._system_prompt: str = "You are a helpful assistant."
        # Lightweight per-session message history (no graph/checkpoint overhead)
        self._histories: dict[str, list] = defaultdict(list)
        logger.info("LLMManager ready.")

    def set_system_prompt(self, prompt: str):
        """
        Updates the system prompt.

        Args:
            prompt: New system prompt text.
        """
        self._system_prompt = prompt
        logger.info("System prompt updated.")

    def get_response(self, user_message: str, session_id: str = "default") -> str:
        """
        Generates an LLM response to the user's message.

        Args:
            user_message: The text spoken by the user.
            session_id: Conversation session ID.

        Returns:
            Text response generated by the LLM.
        """
        logger.info(
            "LLM request - session=%s, message='%s'",
            session_id, user_message[:80],
        )

        history = self._histories[session_id]
        history.append(HumanMessage(content=user_message))

        # Build full message list: system prompt + conversation history
        messages = [SystemMessage(content=self._system_prompt)] + history

        response = self._llm.invoke(messages)
        result = response.content

        # Store AI response in history
        history.append(AIMessage(content=result))

        logger.info("LLM response - '%s'", result[:80])
        return result

    def get_history(self, session_id: str = "default") -> list:
        """
        Returns the message history for a specific session.

        Args:
            session_id: Conversation session ID.

        Returns:
            List of messages.
        """
        return list(self._histories.get(session_id, []))

    def clear_history(self, session_id: str = "default"):
        """
        Clears the message history for a specific session.

        Args:
            session_id: Conversation session ID.
        """
        self._histories.pop(session_id, None)
        logger.info("History cleared for session %s.", session_id)
